services:
  item-service:
    image: item-service:1.0
    build:
      context: ./item-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=itemdb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
      interval: 3s
      timeout: 3s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:9
    volumes:
      - ./db/tables.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/2.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: itemdb
      MYSQL_USER: user01
      MYSQL_PASSWORD: password01
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5