services:
  item-service:
    image: item-service:1.0
    build:
      context: ./item-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=itemdb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
      interval: 3s
      timeout: 3s
      retries: 5