openapi: "3.0.0"
info:
  title: "Items API"
  version: "1.0.0"
paths:
  /items:
    get:
      summary: "List all items"
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Item'
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
